#!/usr/bin/env bash
if [ ! -f "${HOME}/.ssh/id_rsa" ]; then
	ssh-keygen -t rsa -b 4096 -f "${HOME}/.ssh/id_rsa"
fi

if [ ! -f "${HOME}/.ssh/config" ]; then
	if hash -r encfs &>/dev/null && hash -r python &> /dev/null; then
		_temporary_closure() {
			local script_path="$(python -c "import os,sys; print(os.path.realpath(os.path.expanduser(sys.argv[1])))" "${BASH_SOURCE[0]}")"
			local encrypted="${script_path%/*/*}/stow-ignored"
			local plain="$(mktemp -d)"
			echo "Retrieving SSH configuration file"
			if encfs "${encrypted}" "${plain}"; then
				sleep 1
				cp "${plain}/config" "${HOME}/.ssh/config"
				if [ "${OSTYPE:0:6}" = "darwin" ]; then
					umount "${plain}"
				else
					fusermount -u "${plain}"
				fi
				rmdir "${plain}"
			fi
		}
		_temporary_closure
		unset -f _temporary_closure
	fi
fi

if hash -r ssh-agent &> /dev/null; then
	if ! ( sourceIfExists "${HOME}/.ssh/environment" && [ "$(pgrep -n -u "${EUID}" ssh-agent)" =  ${SSH_AGENT_PID} ] ); then
		ssh-agent | sed 's/^echo/#echo/' > "${HOME}/.ssh/environment"
		chmod 600 "${HOME}/.ssh/environment"
		. "${HOME}/.ssh/environment"
		ssh-add
	fi
fi
