#!/usr/bin/env bash
if hash -r docker-machine &> /dev/null; then
	function dmenv() {
		if [[ $# -eq 0 ]]; then
			cat <<-EOE |
			${DOCKER_TLS_VERIFY:+DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}}
			${DOCKER_CERT_PATH:+DOCKER_CERT_PATH=${DOCKER_CERT_PATH}}
			${DOCKER_MACHINE_NAME:+DOCKER_MACHINE_NAME=${DOCKER_MACHINE_NAME}}
			${DOCKER_HOST:+DOCKER_HOST=${DOCKER_HOST}}
			EOE
			tr -s '\n'
		else
			case "$1" in
				-c|--clear)
					unset DOCKER_TLS_VERIFY
					unset DOCKER_CERT_PATH
					unset DOCKER_MACHINE_NAME
					unset DOCKER_HOST
					;;
				-l|--list)
					docker-machine ls -q
					;;
				*)
					eval "$(docker-machine env "$1")"
					;;
			esac
		fi
	}
	export -f dmenv
fi
