#!/usr/bin/env bash
if hash -r docker-machine &> /dev/null; then
	function dmenv() {
		if [[ $# -eq 0 ]]; then
			(cat | tr -s '\n') <<-EOE
			${DOCKER_TLS_VERIFY:+DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}}
			${DOCKER_CERT_PATH:+DOCKER_CERT_PATH=${DOCKER_CERT_PATH}}
			${DOCKER_MACHINE_NAME:+DOCKER_MACHINE_NAME=${DOCKER_MACHINE_NAME}}
			${DOCKER_HOST:+DOCKER_HOST=${DOCKER_HOST}}
			EOE
		else
			case "$1" in
				-c|--clear)
					unset DOCKER_TLS_VERIFY
					unset DOCKER_CERT_PATH
					unset DOCKER_MACHINE_NAME
					unset DOCKER_HOST
					;;
				-l|--list)
					docker-machine ls -q
					;;
				*)
					eval "$(docker-machine env "$1")"
					;;
			esac
		fi
	}
	export -f dmenv
fi

function docker() {
	case "$1" in
		tags)
			shift
			docker run --rm gautaz/docker-tags "$@"
			;;
		*)
			command docker "$@"
			;;
	esac
}
export -f docker

function netshoot() {
	local args=opt
	local opt=()
	local cmd=()
	while [[ $# -gt 0 ]]; do
		case "$1" in
			--)
				if [[ "${args}" = "opt" ]]; then
					args=cmd
				else
					cmd+=("$1")
				fi
				;;
			*)
				if [[ "${args}" = "opt" ]]; then
					opt+=("$1")
				else
					cmd+=("$1")
				fi
				;;
		esac
		shift
	done
	docker run --rm -it "${opt[@]}" nicolaka/netshoot "${cmd[@]}"
}
export -f netshoot
