#!/usr/bin/env bash
if hash -r git &> /dev/null; then
	git config --global alias.conflicts "diff --name-only --diff-filter=U"
	git config --global alias.tree "log --all --decorate --oneline --graph"
	git config --global alias.ignore '!gi() { curl -L -s https://www.gitignore.io/api/$@ ;}; gi'

	git config --global --unset-all user.name
	git config --global --unset-all user.username
	git config --global --unset-all user.email
	git config --global user.useConfigOnly true
	git config --global push.default "simple"
	git config --global core.excludesFile "${HOME}/.gitignore"

	if [ ! -f "${HOME}/.gitignore" ]; then
		_temporary_closure() {
			local giList="vim"
			if [ "${OSTYPE:0:6}" = "darwin" ]; then
				giList="${giList},osx"
			fi
			git ignore "${giList}" > "${HOME}/.gitignore"
		}
		_temporary_closure
		unset -f _temporary_closure
	fi

	if [ "${OSTYPE:0:6}" = "darwin" ] && hash -r git-credential-osxkeychain &> /dev/null; then
		git config --global credential.helper "osxkeychain"
	fi
fi
