#!/bin/sh
if hash -r git &> /dev/null; then
	git config --global diff.renameLimit 20000
	git config --global push.default "simple"

	# Aliases
	git config --global alias.conflicts "diff --name-only --diff-filter=U"
	git config --global alias.ignore '!gi() { curl -L -s https://www.gitignore.io/api/$@ ;}; gi'
	git config --global alias.tree "log --all --decorate --oneline --graph"

	# See https://orrsella.com/2013/08/10/git-using-different-user-emails-for-different-repositories/
	git config --global --unset-all user.name
	git config --global --unset-all user.username
	git config --global --unset-all user.email
	git config --global user.useConfigOnly true

	# Credential helper
	__git_set_default_credential_helper() {
		local default='cache --timeout=300'
		if [[ -n "$1" ]]; then
			echo "No git credential helper available for $1 (using ${default})"
		fi
		git config --global credential.helper "${default}"
	}
	__temporary_closure() {
		local gnome_credential_helper="/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret"
		case "${OSTYPE}" in
			linux*)
				if [[ -x "${gnome_credential_helper}" ]]; then
					git config --global credential.helper "${gnome_credential_helper}"
				else
					__git_set_default_credential_helper "${OSTYPE}"
				fi
				;;
			darwin*)
				if hash -r git-credential-osxkeychain &> /dev/null; then
					git config --global credential.helper "osxkeychain"
				else
					__git_set_default_credential_helper "${OSTYPE}"
				fi
				;;
			*)
				__git_set_default_credential_helper
				;;
		esac
	}
	__temporary_closure
	unset -f __temporary_closure
	unset -f __git_set_default_credential_helper

	# Global .gitignore
	__temporary_closure() {
		local giList="vim"
		if [[ "${OSTYPE}" == darwin* ]]; then
			giList="${giList},osx"
		fi
		git ignore "${giList}" > "${HOME}/.gitignore"
	}
	__temporary_closure
	unset -f __temporary_closure
	git config --global core.excludesFile "${HOME}/.gitignore"
fi
