#!/usr/bin/env bash
if [[ -f "${HOME}/.kube/config" ]]; then
	KUBECONFIG="${HOME}/.kube/config"
fi

if [[ -d "${HOME}/.kube/config.d" ]]; then
	KUBECONFIG="${KUBECONFIG}$(printf ":%s" "${EXTRA_KUBE_CONFIGS[@]}")"
fi

if [[ -n "${KUBECONFIG}" ]]; then
	export KUBECONFIG
fi
