#!/usr/bin/env bash
if hash -r screen 2>/dev/null; then
	ns() {
		local cwd='~'
		[ "${PWD}" != "${HOME}" ] && cwd="${PWD/#${HOME}\//\~\/}"
		local sessionname="$(tac -s / <<< "${cwd}" | tr -s '/\n' '@')"
		screen -d -m -S "${sessionname}"
		echo "${sessionname}"
	}

	nsa() {
		local sessionname="$(ns)"
		screen -r "${sessionname}"
	}
fi
